version: '3'

services:

  web:
    container_name: kob_web
    ports:
      - 9090:80
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
      - search
    links:
      - database
      - search
    environment:
      - APPLICATION_ENVIRONMENT=development
      - DB_HOST=database
      - DB_PORT=3306
      - DB_NAME=klingogbang
      - DB_USER=root
      - DB_PASSWORD=example
    volumes:
      - ./config:/var/www/config
      - ./src:/var/www/src
      - ./public:/var/www/public
      - ./bin:/var/www/bin
      - ./data:/var/www/data
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  database:
    container_name: kob_database
    image: mysql:5.6.41
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 5506:3306
    volumes:
      # - ./data/mysql:/var/lib/mysql
      - ./auto/db/:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=example
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  search:
    container_name: kob_search
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    environment:
      - discovery.type=single-node
    ports:
      - 9201:9200
      - 9301:9300
    volumes:
      - ./data/search/:/usr/share/elasticsearch/data
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
