version: '3'

services:

  web:
    container_name: kob_web
    ports:
      - 8080:80
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    links:
      - database
#    environment:
#      - APPLICATION_ENVIRONMENT=development
#      - DB_HOST=database
#      - DB_PORT=3306
#      - DB_NAME=althingi
#      - DB_NAME_TEST=althingi
#      - DB_USER=root
#      - DB_PASSWORD=example
#      - DB_SETUP=false
#      - CACHE_TYPE=none
#      - SEARCH=none
#      - LOG_PATH=none
#      - QUEUE=none
#      - QUEUE_FORCED=false
    volumes:
#    - ./auto/:/usr/src/auto
#    - ./config/:/usr/src/config
    - .:/var/www
#    - ./public/:/usr/src/public
#    command: bash -c "/usr/src/auto/run-test.sh"

  database:
    container_name: kob_database
    image: mysql:5.6.41
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 5506:3306
    volumes:
    - ./auto/db/:/docker-entrypoint-initdb.d
    environment:
    - MYSQL_ROOT_PASSWORD=example
